### ISSUE TITLE
18.04

### ISSUE THREAD

**Issue by ahyear** [virtualmin/virtualmin-install#11]
Hello,

The new 18.04 LTS is due to be released on April 26 (in a week or so).
Do you know how long it will take (more or less) from then to have an installation script compatible?
Thank you.

**Comment by qooob** [comment]
I would also like to ask adding Fedora to the list. Fedora distro should have all necessary dependencies.

Is this that difficult?

**Comment by swelljoe** [comment]
Ubuntu 18.04 LTS support will likely come a week or so after it is officially released. Maybe a little more or less. I don't know of any changes that will impact Virtualmin (i.e. all the hard stuff, like the systemd change) already happened, so it's probably a very easy process. I probably just need to rebuild a couple of binaries, make new repos, and do a lot of testing.

Fedora is one that I've unofficially supported a few times along the way (19 and 20, I think, most recently), and officially way back in the early days. But, the life cycle is so short, and too many people were using it on servers and then making dumb decisions about their servers when EOL came, like continuing to run outdated software for years. I may unofficially support it again for developers (i.e. me, since I run Fedora on my development laptop) at some point...very likely during the Virtualmin 7 development cycle (I dunno when it'll start, as I need to get some other website stuff finished). Supporting Fedora is perhaps the easiest of all, but having users try to *use* Fedora on servers is disastrous, so I don't do it most of the time, and when I do, I don't advertise it.

**Comment by qooob** [comment]
@swelljoe Thank you, Joe.

> .. too many people were using it on servers and then making dumb decisions about their servers when EOL came, like continuing to run outdated software for years.

I have upgraded already 3 distros with no issues at all. You just run:

```
dnf system-upgrade download --refresh --releasever=27
dnf system-upgrade reboot
```

It takes only 15-20 minutes downtime to run the update.

>  I may unofficially support it again for developers 

That would be good for all, I think. Maybe we'll be able to write an article and post it for Fedora Magazine hoping that they would publish it. I think official support would be good too.

> Supporting Fedora is perhaps the easiest of all, but having users try to use Fedora on servers is disastrous..

Joe, it's not _disastrous_ - it's the stereotype. I can tell you from my experience - Fedora Server as smooth as it can be. Literally super stable and perfect overall. I only once (from 2 years running it) had an issue with _syslog_ package. I figured the issue out in 10 minutes and fixed it. Besides, you can always downgrade to previous version of the package.

**Comment by swelljoe** [comment]
I don't fall back on "I'm older and wiser" as a reason for doing things (or not doing things) very often, but I'm gonna play the "older and wiser" card on this one. ;-)

**Comment by qooob** [comment]
> I don't fall back on "I'm older and wiser"

You are a little bit older but much wiser :wink: 

> but I'm gonna play the "older and wiser" card on this one.

That's alright. I think having larger scale is always better for the project in general, as long as we don't jeopardise overall quality and invest unreasonably much of the time.

**Comment by ahyear** [comment]
hello,
it's a good news. 
do you have any update? ^^ 

thank you

**Comment by swelljoe** [comment]
I'm waiting on a new Webmin devel release to wrap it up (or at least to get it out for testing by users). Hopefully coming soon.

**Comment by jcameron** [comment]
I'm kicking off a new 1.833 devel version now..

**Comment by jcameron** [comment]
Ok, the 1.883 devel version is now available at http://www.webmin.com/devel.html

**Comment by swelljoe** [comment]
Cool. Will run some test installs and send PRs for any additional changes I need.

Thanks, @jcameron !

**Comment by swelljoe** [comment]
Done!

It needs a bit more testing before I call it really done, but I just completed the first successful install on 18.04 LTS and I can't find any problems with the resulting installation (SQLite module needs an update but that'll come today or tomorrow, and not a lot of folks are using it, so probably won't be noticed anyway.)
