### ISSUE TITLE
postfix on ubuntu 18.04

### ISSUE THREAD

**Issue by ahyear** [virtualmin/virtualmin-install#12]
Hello,

On fresh install, after a re-check configuration, i get:
A problem was found with your Postfix virtual maps : No map sources were found in the Postfix configuration

is it due to the installer script or is it a virtualmin issue? (or neither?)

EDIT:
fixed that by adding : 

virtual_alias_maps = hash:/etc/postfix/virtual
to mail.cf 

not sur it's what i had to do.

**Comment by swelljoe** [comment]
It's an installer issue. I'm looking into it.

**Comment by swelljoe** [comment]
This is the same problem as your other ticket. The configuration phase of your installation did not complete. Virtualmin did not finish installing on your system.

You'll probably want to start from scratch (a fresh install of your OS) and we'll work through why it's failing rather than fixing every problem manually. I'm gonna close this one, as I've asked some follow up questions in the other ticket to try to suss out where you installation failed. This system is gonna give you problems until you've got a complete configuration.
