### ISSUE TITLE
Virtualmin on CentOS 8?

### ISSUE THREAD

**Issue by alanmels** [virtualmin/virtualmin-install#37]
I've found this unfinished discussion on the forums: https://forum.virtualmin.com/t/virtualmin-install-sh-support-for-centos-8/104880/37 and couple discussions on github: https://github.com/virtualmin/virtualmin-install/issues/36 and https://github.com/virtualmin/virtualmin-install/issues/33. 

Apparently you, guys, started to helping users to troubleshoot various issues for CentOS 8, I guess it is kind of working (never tried it myself yet). However, the README file on https://github.com/virtualmin/virtualmin-install/blob/master/README.md still lists only CentOS/RHEL/Scientific 6 and 7 as supported systems. So could you please give any ETA for official support of CentOS 8?

**Comment by swelljoe** [comment]
I suppose it's as official as it's going to get. It works and we answer questions about it, and we help Pro users fix any problems in our issue tracker. Still probably has a few quirks (likely fixed in the next couple days when all the new packages go out for Ubuntu 20.04 support as there have been a number of commits to address all the issues we're aware of). The official OS support list is not the README (though I should update the README, too), it's the [Virtualmin OS Support](https://virtualmin.com/os-support.html) page on our website.
