### ISSUE TITLE
ProFTPd error during installation on fresh Ubuntu 16.04.3

### ISSUE THREAD

**Issue by treyturner** [virtualmin/virtualmin-install#6]
I'm trying to install virtualmin 6.0.3 on a Digital Ocean Ubuntu 16.04.3 droplet using the ```--minimal``` flag. The installation proceeds until step 7 of phase 3, which is ProFTPd configuration. Installation halts after this error:

```
[7/17] Configuring ProFTPd                                              █▒▒▒▒▒▒
Use of uninitialized value $hostname in concatenation (.) or string at /usr/share/perl5/Virtualmin/Config/Plugin/ProFTPd.pm line 80.
Use of uninitialized value $hostname in concatenation (.) or string at /usr/share/perl5/Virtualmin/Config/Plugin/ProFTPd.pm line 83.
Error: Failed to list systemd units :
Error
-----
Failed to list systemd units :
-----
▣▣▣ Cleaning up

[SUCCESS] Installation Complete!
[SUCCESS] If there were no errors above, Virtualmin should be ready
[SUCCESS] to configure at ...
```

[virtualmin-install.log.txt](https://github.com/virtualmin/virtualmin-install/files/1236836/virtualmin-install.log.txt)

**Comment by swelljoe** [comment]
I believe this issue was fixed by a change in the slib shell function library (system hostname was not being set correctly). Can you let me know if this still happens?

**Comment by swelljoe** [comment]
I'll assume it's fixed.

**Comment by treyturner** [comment]
I actually got going in this case by enabling swap. Thanks for following up.

**Comment by swelljoe** [comment]
That should also be automatically dealt with now. It'll offer to create a swap file for you, if you have less than 1GB for a full install or 768MB for a minimal install.

We also make it more clear when something has gone wrong in the most recent versions...it's hard to miss that it failed now, as it includes phase information (e.g. "Phase 1 of 3") and steps during configuration (e.g. [3/23]) so if you see if stop before [23/23] or before Phase 3 of 3) you know it bailed early and you'll need to review the log to find out why. That was exactly because of memory issues causing it to silently bail due to the OOM killer stopping the process (so we couldn't even warn about it failing, since the kernel killed it with prejudice), especially on Debian and Ubuntu, because apt-get is a *monster* when it comes to memory usage.
