### ISSUE TITLE
Installation fails on ubuntu 22.04

### ISSUE THREAD

**Issue by ovgray** [virtualmin/virtualmin-install#73]
I have a new server instance at vultr.com with ubuntu 22.04.

The 7.0.0-RC11 installer (edited to put in my vm Pro serial and key) runs without crashing - leaves an install log in /root. 

But I can no longer log in via ssh, even if I do so using the server's ip address. And the web interface is not responsive.

Something about dns resolution is broken. If I go in via a console I find the server is no longer capable of resolving any domain name, including the server's own fqdn. "host" says unable to find servers. Maybe the problem has something to do with the fact that the instance came configured to use systemd-resolve.

I cannot get a copy of the install log without ssh access. In any event, perhaps you could run the install script in a fresh ubuntu 2204 instance from Vultr to see what goes wrong.

**Comment by jcameron** [comment]
What does /etc/resolv.conf contain on your system?

**Comment by ovgray** [comment]
I also cannot copy the contents of /etc/resolv.conf because I have no ssh access. Here is a picture from the console vultr provides:

![IMG_2040](https://user-images.githubusercontent.com/2389376/182005014-025be421-2476-4c6b-a0f0-643f67336a32.jpg)

**Comment by iliajie** [comment]
Does it help if you run `ufw disable` command? I remember there were issues with Ubuntu 22.04 on Vultr, which I reported about two month ago to them. I do not know if those are fixed yet. If not, perhaps we will just address it on our (installer) side.

It was that the connection with the system was lost upon installation of `firewalld` package.

If you need an immediate fix I would suggest looking into solving a problem with `ufw` .. try just purging it, like `apt-get purge ufw` .. or try Linode for example .. it didn't have any issues last time I tried it.

**Comment by iliajie** [comment]
I have given it another try with Vultr Ubuntu 22.04, and it seems that Vultr isn't providing a fully clean state (default) Ubuntu 22.04 instance .. one of the things I noticed is that they _enable_ and configure `ufw` to allow port 22. This is probably a good thing for an ordinary user, I don't know .. but we will have to work around it, as when you install `firewalld` on top of running `ufw` .. well, things go broken.

---

I have patched our install script to make sure we just purge `ufw` before installing Virtualmin related packages to make sure connection won't be broken.

You can give it a try with development version of [`virtualmin-install.sh`](https://raw.githubusercontent.com/virtualmin/virtualmin-install/317e2a0e83ed7c7cf7d626304318a337e66535fc/virtualmin-install.sh) script. It worked flawlessly for me o Vultr too.

❗ Trying this development version of install script won't provide you with any user input (i.e. as you type `y`), because a new install script also requires development version of `slib` script. This is all done in favour to provide a better user experience -- while installation is running pressing keys on the keyboard won't let user to break installer and its look. However, user input is re-enabled for prompts, but that again requires updated dependency library as well to work correctly. All of this will be working as expected in a final Virtualmin 7 release. So, don't get surprised when using this install script and seeing no user input while pressing `y`.

**Comment by iliajie** [comment]
Actually, try [this one](https://raw.githubusercontent.com/virtualmin/virtualmin-install/ce35da6d04d394a6a030da53efc9ac18a7332aec/virtualmin-install.sh) .. as I forgot to use `--assume-yes` on initial patch ..

**Comment by ovgray** [comment]
Thanks. I'll give it a try when I get a chance.

**Comment by ovgray** [comment]
I was able to get back to this today.
I can report that the installation script to which you provided a link appears to have worked on a new Ubuntu 22.04 server instance. I can access virtualmin via https and I can still log in via ssh.
Thank you.
